package site.addzero.vibepocket.codegen

import site.addzero.vibepocket.codegen.ir.*
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class CodeEmitterModelTest {

    private val emitter = CodeEmitter("site.addzero.vibepocket.api.generated")

    // ── File structure ──

    @Test
    fun `model file has auto-generated header comment`() {
        val model = ModelIR("FavoriteItem", emptyList(), null)
        val output = emitter.emitModel(model).toString()
        assertTrue(output.contains("Auto-generated by OpenAPI Ktorfit Codegen. Do not edit."))
    }

    @Test
    fun `model file has models sub-package`() {
        val model = ModelIR("FavoriteItem", emptyList(), null)
        val fileSpec = emitter.emitModel(model)
        assertEquals("site.addzero.vibepocket.api.generated.models", fileSpec.packageName)
    }

    @Test
    fun `model file name matches class name`() {
        val model = ModelIR("FavoriteItem", emptyList(), null)
        val fileSpec = emitter.emitModel(model)
        assertEquals("FavoriteItem", fileSpec.name)
    }

    // ── @Serializable and data class ──

    @Test
    fun `model has @Serializable annotation`() {
        val model = ModelIR("FavoriteItem", listOf(
            PropertyIR("id", TypeRef.Primitive("String"), required = true, defaultValue = null, description = null)
        ), null)
        val output = emitter.emitModel(model).toString()
        assertTrue(output.contains("@Serializable"), "Expected @Serializable, got:\n$output")
    }

    @Test
    fun `model is a data class`() {
        val model = ModelIR("FavoriteItem", listOf(
            PropertyIR("id", TypeRef.Primitive("String"), required = true, defaultValue = null, description = null)
        ), null)
        val output = emitter.emitModel(model).toString()
        assertTrue(output.contains("data class FavoriteItem"), "Expected data class, got:\n$output")
    }

    @Test
    fun `model imports kotlinx serialization Serializable`() {
        val model = ModelIR("FavoriteItem", listOf(
            PropertyIR("id", TypeRef.Primitive("String"), required = true, defaultValue = null, description = null)
        ), null)
        val output = emitter.emitModel(model).toString()
        assertTrue(output.contains("import kotlinx.serialization.Serializable"), "Expected Serializable import, got:\n$output")
    }

    // ── Required / non-nullable properties ──

    @Test
    fun `required property is non-nullable without default`() {
        val model = ModelIR("TestModel", listOf(
            PropertyIR("id", TypeRef.Primitive("String"), required = true, defaultValue = null, description = null)
        ), null)
        val output = emitter.emitModel(model).toString()
        assertTrue(output.contains("val id: String"), "Expected non-nullable id: String, got:\n$output")
        assertTrue(!output.contains("id: String?"), "Should not be nullable, got:\n$output")
    }

    // ── Optional / nullable properties ──

    @Test
    fun `optional property is nullable with default null`() {
        val model = ModelIR("TestModel", listOf(
            PropertyIR("count", TypeRef.Primitive("Int"), required = false, defaultValue = null, description = null)
        ), null)
        val output = emitter.emitModel(model).toString()
        assertTrue(output.contains("count: Int? = null"), "Expected nullable with default null, got:\n$output")
    }

    // ── Default values ──

    @Test
    fun `required property with defaultValue uses that default`() {
        val model = ModelIR("TestModel", listOf(
            PropertyIR("active", TypeRef.Primitive("Boolean"), required = true, defaultValue = "true", description = null)
        ), null)
        val output = emitter.emitModel(model).toString()
        assertTrue(output.contains("active: Boolean = true"), "Expected default value true, got:\n$output")
    }

    @Test
    fun `optional property with explicit defaultValue uses that instead of null`() {
        val model = ModelIR("TestModel", listOf(
            PropertyIR("name", TypeRef.Primitive("String"), required = false, defaultValue = "\"unknown\"", description = null)
        ), null)
        val output = emitter.emitModel(model).toString()
        assertTrue(output.contains("name: String? = \"unknown\""), "Expected explicit default, got:\n$output")
    }

    // ── KDoc ──

    @Test
    fun `model KDoc is generated from description`() {
        val model = ModelIR("FavoriteItem", listOf(
            PropertyIR("id", TypeRef.Primitive("String"), required = true, defaultValue = null, description = null)
        ), "A favorite item in the collection")
        val output = emitter.emitModel(model).toString()
        assertTrue(output.contains("A favorite item in the collection"), "Expected KDoc, got:\n$output")
    }

    @Test
    fun `no KDoc when description is null`() {
        val model = ModelIR("FavoriteItem", listOf(
            PropertyIR("id", TypeRef.Primitive("String"), required = true, defaultValue = null, description = null)
        ), null)
        val output = emitter.emitModel(model).toString()
        assertTrue(!output.contains("/**"), "Should not contain KDoc, got:\n$output")
    }

    // ── Type mappings in model context ──

    @Test
    fun `List type property is generated correctly`() {
        val model = ModelIR("TestModel", listOf(
            PropertyIR("tags", TypeRef.ListType(TypeRef.Primitive("String")), required = true, defaultValue = null, description = null)
        ), null)
        val output = emitter.emitModel(model).toString()
        assertTrue(output.contains("val tags: List<String>"), "Expected List<String>, got:\n$output")
    }

    @Test
    fun `Reference type property is generated correctly`() {
        val model = ModelIR("TestModel", listOf(
            PropertyIR("item", TypeRef.Reference("FavoriteItem"), required = true, defaultValue = null, description = null)
        ), null)
        val output = emitter.emitModel(model).toString()
        assertTrue(output.contains("val item: FavoriteItem"), "Expected FavoriteItem type, got:\n$output")
    }

    @Test
    fun `JsonElement fallback type property is generated correctly`() {
        val model = ModelIR("TestModel", listOf(
            PropertyIR("raw", TypeRef.JsonElement, required = true, defaultValue = null, description = null)
        ), null)
        val output = emitter.emitModel(model).toString()
        assertTrue(output.contains("val raw: JsonElement"), "Expected JsonElement type, got:\n$output")
    }

    // ── emit() integration with models ──

    @Test
    fun `emit includes model files`() {
        val model = ModelIR("FavoriteItem", listOf(
            PropertyIR("id", TypeRef.Primitive("String"), required = true, defaultValue = null, description = null)
        ), null)
        val ir = OpenApiIR(interfaces = emptyList(), models = listOf(model))
        val files = emitter.emit(ir)
        assertEquals(1, files.size)
        assertEquals("FavoriteItem", files[0].name)
        assertEquals("site.addzero.vibepocket.api.generated.models", files[0].packageName)
    }

    @Test
    fun `emit includes both interfaces and models`() {
        val iface = ApiInterfaceIR("FavoritesApi", emptyList())
        val model = ModelIR("FavoriteItem", listOf(
            PropertyIR("id", TypeRef.Primitive("String"), required = true, defaultValue = null, description = null)
        ), null)
        val ir = OpenApiIR(interfaces = listOf(iface), models = listOf(model))
        val files = emitter.emit(ir)
        assertEquals(2, files.size)
        assertEquals("FavoritesApi", files[0].name)
        assertEquals("FavoriteItem", files[1].name)
    }

    // ── Full example matching design doc ──

    @Test
    fun `full model matches design doc example`() {
        val model = ModelIR("FavoriteItem", listOf(
            PropertyIR("id", TypeRef.Primitive("String"), required = true, defaultValue = null, description = null),
            PropertyIR("name", TypeRef.Primitive("String"), required = true, defaultValue = null, description = null),
            PropertyIR("count", TypeRef.Primitive("Int"), required = false, defaultValue = null, description = null),
            PropertyIR("active", TypeRef.Primitive("Boolean"), required = true, defaultValue = "true", description = null)
        ), null)
        val output = emitter.emitModel(model).toString()

        assertTrue(output.contains("@Serializable"), "Expected @Serializable")
        assertTrue(output.contains("data class FavoriteItem"), "Expected data class FavoriteItem")
        assertTrue(output.contains("val id: String"), "Expected val id: String")
        assertTrue(output.contains("val name: String"), "Expected val name: String")
        assertTrue(output.contains("count: Int? = null"), "Expected count: Int? = null")
        assertTrue(output.contains("active: Boolean = true"), "Expected active: Boolean = true")
        assertTrue(output.contains("import kotlinx.serialization.Serializable"), "Expected Serializable import")
        assertTrue(output.contains("Auto-generated by OpenAPI Ktorfit Codegen"), "Expected header comment")
    }
}
