package site.addzero.vibepocket.codegen

import site.addzero.vibepocket.codegen.ir.*
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class CodeEmitterInterfaceTest {

    private val emitter = CodeEmitter("site.addzero.vibepocket.api.generated")

    // ── File structure ──

    @Test
    fun `generated file has auto-generated header comment`() {
        val iface = ApiInterfaceIR("FavoritesApi", emptyList())
        val fileSpec = emitter.emitInterface(iface)
        val output = fileSpec.toString()
        assertTrue(output.contains("Auto-generated by OpenAPI Ktorfit Codegen. Do not edit."))
    }

    @Test
    fun `generated file has correct package declaration`() {
        val iface = ApiInterfaceIR("FavoritesApi", emptyList())
        val fileSpec = emitter.emitInterface(iface)
        assertEquals("site.addzero.vibepocket.api.generated", fileSpec.packageName)
    }

    @Test
    fun `generated file name matches interface name`() {
        val iface = ApiInterfaceIR("HistoryApi", emptyList())
        val fileSpec = emitter.emitInterface(iface)
        assertEquals("HistoryApi", fileSpec.name)
    }

    // ── HTTP method annotations ──

    @Test
    fun `GET operation generates @GET annotation with path`() {
        val op = OperationIR("getFavorites", HttpMethod.GET, "api/favorites", null, emptyList(), null, TypeRef.Unit)
        val iface = ApiInterfaceIR("FavoritesApi", listOf(op))
        val output = emitter.emitInterface(iface).toString()
        assertTrue(output.contains("@GET(\"api/favorites\")"))
    }

    @Test
    fun `POST operation generates @POST annotation`() {
        val op = OperationIR("addFavorite", HttpMethod.POST, "api/favorites", null, emptyList(), TypeRef.Reference("FavoriteRequest"), TypeRef.Reference("FavoriteItem"))
        val iface = ApiInterfaceIR("FavoritesApi", listOf(op))
        val output = emitter.emitInterface(iface).toString()
        assertTrue(output.contains("@POST(\"api/favorites\")"))
    }

    @Test
    fun `PUT operation generates @PUT annotation`() {
        val op = OperationIR("updateItem", HttpMethod.PUT, "api/items/{id}", null, emptyList(), null, TypeRef.Unit)
        val iface = ApiInterfaceIR("ItemsApi", listOf(op))
        val output = emitter.emitInterface(iface).toString()
        assertTrue(output.contains("@PUT(\"api/items/{id}\")"))
    }

    @Test
    fun `DELETE operation generates @DELETE annotation`() {
        val op = OperationIR("removeFavorite", HttpMethod.DELETE, "api/favorites/{trackId}", null, emptyList(), null, TypeRef.Unit)
        val iface = ApiInterfaceIR("FavoritesApi", listOf(op))
        val output = emitter.emitInterface(iface).toString()
        assertTrue(output.contains("@DELETE(\"api/favorites/{trackId}\")"))
    }

    @Test
    fun `PATCH operation generates @PATCH annotation`() {
        val op = OperationIR("patchItem", HttpMethod.PATCH, "api/items/{id}", null, emptyList(), null, TypeRef.Unit)
        val iface = ApiInterfaceIR("ItemsApi", listOf(op))
        val output = emitter.emitInterface(iface).toString()
        assertTrue(output.contains("@PATCH(\"api/items/{id}\")"))
    }

    // ── Suspend functions ──

    @Test
    fun `generated functions are suspend and abstract`() {
        val op = OperationIR("getFavorites", HttpMethod.GET, "api/favorites", null, emptyList(), null, TypeRef.Unit)
        val iface = ApiInterfaceIR("FavoritesApi", listOf(op))
        val output = emitter.emitInterface(iface).toString()
        assertTrue(output.contains("public suspend fun getFavorites()"))
    }

    // ── Parameter annotations ──

    @Test
    fun `@Path parameter is generated correctly`() {
        val params = listOf(ParameterIR("trackId", ParameterLocation.PATH, TypeRef.Primitive("String"), required = true))
        val op = OperationIR("removeFavorite", HttpMethod.DELETE, "api/favorites/{trackId}", null, params, null, TypeRef.Unit)
        val iface = ApiInterfaceIR("FavoritesApi", listOf(op))
        val output = emitter.emitInterface(iface).toString()
        assertTrue(output.contains("@Path(\"trackId\")"), "Expected @Path annotation, got:\n$output")
        assertTrue(output.contains("trackId: String"), "Expected trackId: String param, got:\n$output")
    }

    @Test
    fun `@Query parameter is generated correctly`() {
        val params = listOf(ParameterIR("page", ParameterLocation.QUERY, TypeRef.Primitive("Int"), required = false))
        val op = OperationIR("getFavorites", HttpMethod.GET, "api/favorites", null, params, null, TypeRef.ListType(TypeRef.Reference("FavoriteItem")))
        val iface = ApiInterfaceIR("FavoritesApi", listOf(op))
        val output = emitter.emitInterface(iface).toString()
        assertTrue(output.contains("@Query(\"page\")"), "Expected @Query annotation, got:\n$output")
        assertTrue(output.contains("page: Int? = null"), "Expected nullable page param, got:\n$output")
    }

    @Test
    fun `@Header parameter is generated correctly`() {
        val params = listOf(ParameterIR("Authorization", ParameterLocation.HEADER, TypeRef.Primitive("String"), required = true))
        val op = OperationIR("getSecure", HttpMethod.GET, "api/secure", null, params, null, TypeRef.Unit)
        val iface = ApiInterfaceIR("SecureApi", listOf(op))
        val output = emitter.emitInterface(iface).toString()
        assertTrue(output.contains("@Header(\"Authorization\")"), "Expected @Header annotation, got:\n$output")
        assertTrue(output.contains("Authorization: String"), "Expected Authorization: String param, got:\n$output")
    }

    // ── @Body parameter ──

    @Test
    fun `@Body parameter is generated for request body`() {
        val op = OperationIR("addFavorite", HttpMethod.POST, "api/favorites", null, emptyList(), TypeRef.Reference("FavoriteRequest"), TypeRef.Reference("FavoriteItem"))
        val iface = ApiInterfaceIR("FavoritesApi", listOf(op))
        val output = emitter.emitInterface(iface).toString()
        assertTrue(output.contains("@Body"), "Expected @Body annotation, got:\n$output")
        assertTrue(output.contains("body: FavoriteRequest"), "Expected body param, got:\n$output")
    }

    @Test
    fun `no @Body parameter when requestBody is null`() {
        val op = OperationIR("getFavorites", HttpMethod.GET, "api/favorites", null, emptyList(), null, TypeRef.Unit)
        val iface = ApiInterfaceIR("FavoritesApi", listOf(op))
        val output = emitter.emitInterface(iface).toString()
        assertTrue(!output.contains("@Body"), "Should not contain @Body, got:\n$output")
    }

    // ── Return types ──

    @Test
    fun `return type Unit when no response body`() {
        val op = OperationIR("removeFavorite", HttpMethod.DELETE, "api/favorites/{trackId}", null, emptyList(), null, TypeRef.Unit)
        val iface = ApiInterfaceIR("FavoritesApi", listOf(op))
        val output = emitter.emitInterface(iface).toString()
        assertTrue(output.contains(": Unit"), "Expected Unit return type, got:\n$output")
    }

    @Test
    fun `return type maps Reference correctly`() {
        val op = OperationIR("addFavorite", HttpMethod.POST, "api/favorites", null, emptyList(), TypeRef.Reference("FavoriteRequest"), TypeRef.Reference("FavoriteItem"))
        val iface = ApiInterfaceIR("FavoritesApi", listOf(op))
        val output = emitter.emitInterface(iface).toString()
        assertTrue(output.contains(": FavoriteItem"), "Expected FavoriteItem return type, got:\n$output")
    }

    @Test
    fun `return type maps List correctly`() {
        val op = OperationIR("getFavorites", HttpMethod.GET, "api/favorites", null, emptyList(), null, TypeRef.ListType(TypeRef.Reference("FavoriteItem")))
        val iface = ApiInterfaceIR("FavoritesApi", listOf(op))
        val output = emitter.emitInterface(iface).toString()
        assertTrue(output.contains(": List<FavoriteItem>"), "Expected List<FavoriteItem> return type, got:\n$output")
    }

    @Test
    fun `return type maps primitive correctly`() {
        val op = OperationIR("getCount", HttpMethod.GET, "api/count", null, emptyList(), null, TypeRef.Primitive("Int"))
        val iface = ApiInterfaceIR("CountApi", listOf(op))
        val output = emitter.emitInterface(iface).toString()
        assertTrue(output.contains(": Int"), "Expected Int return type, got:\n$output")
    }

    @Test
    fun `return type maps JsonElement for unknown types`() {
        val op = OperationIR("getRaw", HttpMethod.GET, "api/raw", null, emptyList(), null, TypeRef.JsonElement)
        val iface = ApiInterfaceIR("RawApi", listOf(op))
        val output = emitter.emitInterface(iface).toString()
        assertTrue(output.contains(": JsonElement"), "Expected JsonElement return type, got:\n$output")
    }

    // ── KDoc comments ──

    @Test
    fun `KDoc is generated from summary`() {
        val op = OperationIR("getFavorites", HttpMethod.GET, "api/favorites", "List all favorites", emptyList(), null, TypeRef.Unit)
        val iface = ApiInterfaceIR("FavoritesApi", listOf(op))
        val output = emitter.emitInterface(iface).toString()
        assertTrue(output.contains("List all favorites"), "Expected KDoc with summary, got:\n$output")
    }

    @Test
    fun `no KDoc when summary is null`() {
        val op = OperationIR("getFavorites", HttpMethod.GET, "api/favorites", null, emptyList(), null, TypeRef.Unit)
        val iface = ApiInterfaceIR("FavoritesApi", listOf(op))
        val output = emitter.emitInterface(iface).toString()
        assertTrue(!output.contains("/**"), "Should not contain KDoc, got:\n$output")
    }

    @Test
    fun `no KDoc when summary is blank`() {
        val op = OperationIR("getFavorites", HttpMethod.GET, "api/favorites", "  ", emptyList(), null, TypeRef.Unit)
        val iface = ApiInterfaceIR("FavoritesApi", listOf(op))
        val output = emitter.emitInterface(iface).toString()
        assertTrue(!output.contains("/**"), "Should not contain KDoc for blank summary, got:\n$output")
    }

    // ── Nullable / optional parameters ──

    @Test
    fun `required parameter is non-nullable`() {
        val params = listOf(ParameterIR("id", ParameterLocation.PATH, TypeRef.Primitive("String"), required = true))
        val op = OperationIR("getById", HttpMethod.GET, "api/{id}", null, params, null, TypeRef.Unit)
        val iface = ApiInterfaceIR("TestApi", listOf(op))
        val output = emitter.emitInterface(iface).toString()
        assertTrue(output.contains("id: String"), "Expected non-nullable param, got:\n$output")
        assertTrue(!output.contains("id: String?"), "Should not be nullable, got:\n$output")
    }

    @Test
    fun `optional parameter is nullable with default null`() {
        val params = listOf(ParameterIR("limit", ParameterLocation.QUERY, TypeRef.Primitive("Int"), required = false))
        val op = OperationIR("getItems", HttpMethod.GET, "api/items", null, params, null, TypeRef.Unit)
        val iface = ApiInterfaceIR("TestApi", listOf(op))
        val output = emitter.emitInterface(iface).toString()
        assertTrue(output.contains("limit: Int? = null"), "Expected nullable param with default null, got:\n$output")
    }

    // ── emit() integration ──

    @Test
    fun `emit returns FileSpec list for all interfaces`() {
        val iface1 = ApiInterfaceIR("FavoritesApi", emptyList())
        val iface2 = ApiInterfaceIR("HistoryApi", emptyList())
        val ir = OpenApiIR(interfaces = listOf(iface1, iface2), models = emptyList())
        val files = emitter.emit(ir)
        assertEquals(2, files.size)
        assertEquals("FavoritesApi", files[0].name)
        assertEquals("HistoryApi", files[1].name)
    }

    @Test
    fun `emit returns empty list for no interfaces`() {
        val ir = OpenApiIR(interfaces = emptyList(), models = emptyList())
        val files = emitter.emit(ir)
        assertTrue(files.isEmpty())
    }

    // ── Full example matching design doc ──

    @Test
    fun `full interface matches design doc example`() {
        val ops = listOf(
            OperationIR(
                "getFavorites", HttpMethod.GET, "api/favorites", "List all favorites",
                listOf(ParameterIR("page", ParameterLocation.QUERY, TypeRef.Primitive("Int"), required = false)),
                null, TypeRef.ListType(TypeRef.Reference("FavoriteItem"))
            ),
            OperationIR(
                "addFavorite", HttpMethod.POST, "api/favorites", null,
                emptyList(), TypeRef.Reference("FavoriteRequest"), TypeRef.Reference("FavoriteItem")
            ),
            OperationIR(
                "removeFavorite", HttpMethod.DELETE, "api/favorites/{trackId}", null,
                listOf(ParameterIR("trackId", ParameterLocation.PATH, TypeRef.Primitive("String"), required = true)),
                null, TypeRef.Unit
            )
        )
        val iface = ApiInterfaceIR("FavoritesApi", ops)
        val output = emitter.emitInterface(iface).toString()

        // Verify structure
        assertTrue(output.contains("interface FavoritesApi"))
        assertTrue(output.contains("@GET(\"api/favorites\")"))
        assertTrue(output.contains("suspend fun getFavorites"))
        assertTrue(output.contains("@Query(\"page\") page: Int? = null"))
        assertTrue(output.contains(": List<FavoriteItem>"))
        assertTrue(output.contains("@POST(\"api/favorites\")"))
        assertTrue(output.contains("@Body body: FavoriteRequest"))
        assertTrue(output.contains(": FavoriteItem"))
        assertTrue(output.contains("@DELETE(\"api/favorites/{trackId}\")"))
        assertTrue(output.contains("@Path(\"trackId\") trackId: String"))
        assertTrue(output.contains(": Unit"))
        assertTrue(output.contains("List all favorites"))
    }
}
