package site.addzero.vibepocket.codegen

import com.squareup.kotlinpoet.*
import site.addzero.vibepocket.codegen.ir.*

/**
 * 使用 KotlinPoet 将 IR 转换为 Kotlin 源文件。
 */
class CodeEmitter(
    private val packageName: String
) {

    companion object {
        private const val FILE_HEADER = "Auto-generated by OpenAPI Ktorfit Codegen. Do not edit."
        private const val KTORFIT_HTTP_PACKAGE = "de.jensklingenberg.ktorfit.http"
    }

    /**
     * 将完整的 OpenApiIR 转换为 FileSpec 列表。
     */
    fun emit(ir: OpenApiIR): List<FileSpec> {
        val files = mutableListOf<FileSpec>()
        for (iface in ir.interfaces) {
            files.add(emitInterface(iface))
        }
        for (model in ir.models) {
            files.add(emitModel(model))
        }
        return files
    }

    /**
     * 生成单个 Ktorfit 注解的 interface 文件。
     */
    internal fun emitInterface(iface: ApiInterfaceIR): FileSpec {
        val typeSpec = TypeSpec.interfaceBuilder(iface.name)
        for (operation in iface.operations) {
            typeSpec.addFunction(buildFunction(operation))
        }
        return FileSpec.builder(packageName, iface.name)
            .addFileComment(FILE_HEADER)
            .addType(typeSpec.build())
            .build()
    }

    /**
     * 生成单个 @Serializable data class 文件。
     */
    internal fun emitModel(model: ModelIR): FileSpec {
        val modelPackage = "$packageName.models"
        val serializableAnnotation = AnnotationSpec.builder(
            ClassName("kotlinx.serialization", "Serializable")
        ).build()

        val classBuilder = TypeSpec.classBuilder(model.name)
            .addModifiers(KModifier.DATA)
            .addAnnotation(serializableAnnotation)

        // KDoc from model description
        if (!model.description.isNullOrBlank()) {
            classBuilder.addKdoc("%L", model.description)
        }

        val constructorBuilder = FunSpec.constructorBuilder()
        for (prop in model.properties) {
            val baseTypeName = resolveTypeName(prop.type)
            val typeName = if (prop.required) baseTypeName else baseTypeName.copy(nullable = true)

            val paramBuilder = ParameterSpec.builder(prop.name, typeName)

            if (prop.required) {
                if (prop.defaultValue != null) {
                    paramBuilder.defaultValue(CodeBlock.of(prop.defaultValue))
                }
            } else {
                if (prop.defaultValue != null) {
                    paramBuilder.defaultValue(CodeBlock.of(prop.defaultValue))
                } else {
                    paramBuilder.defaultValue("null")
                }
            }

            val propertyBuilder = PropertySpec.builder(prop.name, typeName)
                .initializer(prop.name)

            if (!prop.description.isNullOrBlank()) {
                propertyBuilder.addKdoc("%L", prop.description)
            }

            constructorBuilder.addParameter(paramBuilder.build())
            classBuilder.addProperty(propertyBuilder.build())
        }

        classBuilder.primaryConstructor(constructorBuilder.build())

        return FileSpec.builder(modelPackage, model.name)
            .addFileComment(FILE_HEADER)
            .addType(classBuilder.build())
            .build()
    }

    private fun buildFunction(op: OperationIR): FunSpec {
        val builder = FunSpec.builder(op.functionName)
            .addModifiers(KModifier.SUSPEND, KModifier.ABSTRACT)

        // HTTP method annotation with path
        builder.addAnnotation(
            AnnotationSpec.builder(ClassName(KTORFIT_HTTP_PACKAGE, op.httpMethod.name))
                .addMember("%S", op.path)
                .build()
        )

        // KDoc from summary
        if (!op.summary.isNullOrBlank()) {
            builder.addKdoc("%L", op.summary)
        }

        // Parameters: @Path, @Query, @Header
        for (param in op.parameters) {
            val annotationClass = when (param.location) {
                ParameterLocation.PATH -> "Path"
                ParameterLocation.QUERY -> "Query"
                ParameterLocation.HEADER -> "Header"
            }
            val annotation = AnnotationSpec.builder(ClassName(KTORFIT_HTTP_PACKAGE, annotationClass))
                .addMember("%S", param.name)
                .build()

            var typeName = resolveTypeName(param.type)
            if (!param.required) {
                typeName = typeName.copy(nullable = true)
            }

            val paramSpec = ParameterSpec.builder(param.name, typeName)
                .addAnnotation(annotation)
            if (!param.required) {
                paramSpec.defaultValue("null")
            }
            builder.addParameter(paramSpec.build())
        }

        // Request body: @Body
        op.requestBody?.let { bodyType ->
            val annotation = AnnotationSpec.builder(ClassName(KTORFIT_HTTP_PACKAGE, "Body")).build()
            builder.addParameter(
                ParameterSpec.builder("body", resolveTypeName(bodyType))
                    .addAnnotation(annotation)
                    .build()
            )
        }

        // Return type
        builder.returns(resolveTypeName(op.responseType))

        return builder.build()
    }

    /**
     * 将 TypeRef 映射为 KotlinPoet TypeName。
     */
    internal fun resolveTypeName(typeRef: TypeRef): TypeName = when (typeRef) {
        is TypeRef.Primitive -> when (typeRef.kotlinType) {
            "String" -> String::class.asTypeName()
            "Int" -> Int::class.asTypeName()
            "Long" -> Long::class.asTypeName()
            "Double" -> Double::class.asTypeName()
            "Float" -> Float::class.asTypeName()
            "Boolean" -> Boolean::class.asTypeName()
            else -> ClassName("kotlin", typeRef.kotlinType)
        }
        is TypeRef.ListType -> List::class.asClassName().parameterizedBy(resolveTypeName(typeRef.itemType))
        is TypeRef.Reference -> ClassName("$packageName.models", typeRef.modelName)
        is TypeRef.JsonElement -> ClassName("kotlinx.serialization.json", "JsonElement")
        is TypeRef.Unit -> Unit::class.asTypeName()
    }
}
